// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiuHQgMP7Zk1rHO2kGWsfPWzYgbOsg_Hk',
    appId: '1:406338160857:web:8c89caea035c329ff896c8',
    messagingSenderId: '406338160857',
    projectId: 'spotifyk-20dba',
    authDomain: 'spotifyk-20dba.firebaseapp.com',
    storageBucket: 'spotifyk-20dba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJu4K4DRTO7Fi4QTpwi5-S6ELdjh8JWL0',
    appId: '1:406338160857:android:da88d88cc6ea3160f896c8',
    messagingSenderId: '406338160857',
    projectId: 'spotifyk-20dba',
    storageBucket: 'spotifyk-20dba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx4lCocBArU5OCFYtLki_VFhWQh04qmd4',
    appId: '1:406338160857:ios:1541a6f95325adbaf896c8',
    messagingSenderId: '406338160857',
    projectId: 'spotifyk-20dba',
    storageBucket: 'spotifyk-20dba.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx4lCocBArU5OCFYtLki_VFhWQh04qmd4',
    appId: '1:406338160857:ios:e3eeb286c950f611f896c8',
    messagingSenderId: '406338160857',
    projectId: 'spotifyk-20dba',
    storageBucket: 'spotifyk-20dba.appspot.com',
    iosBundleId: 'com.example.spotifyProject.RunnerTests',
  );
}
